baseurl = "http://mikebroadway.com"  # Include trailing slash
title = "Photographs"
theme = "newsroom"
author = "Mike Broadway"
copyright = "Copyright © 2019, Mike Broadway"
canonifyurls = true
paginate = 10

# ids used below are not valid. Replace with valid ones
[params]
  # ga_analytics = "" # google analytics ID e.g UA-116386578-1
  
  # ga_verify = "" # google verification code e.g 5jb-rxeBfITeJQKOuUss3ud6FPGTxXkCho-ZN5qlrZg
  # twitter = "" # twitter handle e.g @weru

  subTitle = "Mike Broadway"
